name: CI/CD Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Si necesitas build (p.ej. npm run build), descomenta estas líneas:
      #- name: Set up Node.js
      #  uses: actions/setup-node@v3
      #  with: { node-version: '18' }
      #
      #- name: Install & Build
      #  run: |
      #    npm ci
      #    npm run build

      - name: Deploy to Firebase Hosting 🚀
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "gmailapi-443221"
          channelId: "live"
