name: Deploy PROD (Firebase Hosting)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to PROD
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRO }}"
          projectId: "gmailapi-443221"
          target: "prod"
          channelId: "live"
