name: Deploy PRE (Firebase Hosting)

on:
  push:
    branches: [ pre ]
  workflow_dispatch:

jobs:
  deploy-pre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set asset version
        run: echo "ASSET_VERSION=${GITHUB_SHA::7}-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Inject asset version into HTML
        run: |
          find site -name "*.html" -print0 | xargs -0 sed -i "s/%ASSET_VERSION%/${ASSET_VERSION}/g"

      - name: Append version to ESM imports
        run: |
          node -e "
          const fs=require('fs'), path=require('path');
          const ASSET=process.env.ASSET_VERSION;
          function walk(dir){
            for(const e of fs.readdirSync(dir,{withFileTypes:true})){
              const p=path.join(dir,e.name);
              if(e.isDirectory()) walk(p);
              else if(p.endsWith('.js')){
                let s=fs.readFileSync(p,'utf8');
                // from '.../x.js'
                s=s.replace(/(from\\s+['\"])(\\/?js\\/[^'\"\\n]+\\.js)(['\"])/g, (_,a,b,c)=> a + (b.includes('?v=')?b:`${b}?v=${ASSET}`) + c);
                s=s.replace(/(from\\s+['\"])(\\.\\.?(?:\\/)[^'\"\\n]+\\.js)(['\"])/g, (_,a,b,c)=> a + (b.includes('?v=')?b:`${b}?v=${ASSET}`) + c);
                // dynamic import('.../x.js')
                s=s.replace(/(import\\(['\"])(\\/?js\\/[^'\"\\n]+\\.js)(['\"]\\))/g, (_,a,b,c)=> a + (b.includes('?v=')?b:`${b}?v=${ASSET}`) + c);
                s=s.replace(/(import\\(['\"])(\\.\\.?(?:\\/)[^'\"\\n]+\\.js)(['\"]\\))/g, (_,a,b,c)=> a + (b.includes('?v=')?b:`${b}?v=${ASSET}`) + c);
                fs.writeFileSync(p,s);
              }
            }
          }
          walk('site/js');
          "

      - name: Deploy to PRE
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRE }}"
          projectId: "gmailapi-pre"
          target: "pre"         # target de hosting definido con firebase target:apply
          channelId: "live"
