name: Deploy PRE (Firebase Hosting)

on:
  push:
    branches: [ pre ]
  workflow_dispatch:

jobs:
  deploy-pre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to PRE
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRE }}"
          projectId: "gmailapi-pre"
          target: "pre"         # target de hosting definido con firebase target:apply
          channelId: "live"
